import Navbar from "@/components/Navbar";
import { NextAuthProvider } from "./provider";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <NextAuthProvider>
          <div>
            <Navbar></Navbar>
            <div>{children}</div>
          </div>
        </NextAuthProvider>
      </body>
    </html>
  );
}
